api/README.md
api/endpoints/question.py
api/server.py
app/README.md
app/components/TimelineExplorer.js
app/components/questions/Sample.js
app/pages/explorer.js
app/pages/questions.js
app/pages/questions/[id].js
app/site/questions.js
app/styles/app.css
docs/README.md
docs/eda.md
docs/flask.md
docs/new_endpoint.md
docs/new_question.md
docs/react.md
docs/recharts.md
docs/testing.md

**Questions** is section of TransitHealth with custom data stories. Each engineer will pick their own topic (a question about transit and public health they want to explore with data) and build a full-stack, end-to-end feature for it.
1. Add data to the offline pipeline
2. Add an endpoint to the backend API
3. Add a component to the frontend app
Then visitors will be able to browse through questions.
This PR sets up the basic parts of the codebase to allow for development of questions. The next PR will be an example of implementing a new question!

Setup Development for Questions

---

.gitignore
README.md
api/README.md
api/dev.sh
api/scripts/resize.sh
api/scripts/setup.sh
docs/README.md
docs/pages/cloud9.md
docs/pages/makefiles.md
docs/pages/new_endpoint.md
docs/pages/setup.md
docs/pages/time_api_requests.md
pipeline/Makefile

- Write documentation for creating a Cloud9 environment
- Write mostly-automatic script to setup TransitHealth on a new Cloud9 environment
- Copy script from AWS for resizing Elastic Block Storage instance
- Write a script to start the Flask server in development mode
- Fix Makefile commands to rebuild after unpacking archive
- Fix .gitignore to exclude archive folder
- Remove stray heading from Makefile documentation

Add setup guide for Cloud9

---

api/endpoints/community.py
api/endpoints/fake.py
api/endpoints/index.py
api/endpoints/question.py
api/endpoints/rideshare.py
api/endpoints/weekly.py
api/server.py
app/components/Notification.js
app/components/questions/TemplateWithPieChart.js
app/dev.sh
app/site/questions.js
app/site/theme.js
app/styles/app.css

In week two, when interns start working on a data question, this will be one of the examples they can copy and work off of.
This PR adds an example using a pie chart. Next week, I plan to add four more examples:
- Line Chart
- Scatter Chart
- Bar Chart
- Chicago Map Chart

Add a template data question using a pie chart.

---

api/scripts/setup.sh
docs/README.md
docs/pages/cloud9.md
docs/pages/commands.md
docs/pages/new_endpoint.md
docs/pages/new_question.md
docs/pages/time_api_requests.md
run.sh

Adding the run alias makes it easier to run common commands. No more switching around directories to make sure you are in the right subdirectory.

Create run command for convenience.

---

pipeline/Makefile
pipeline/extract/belonging.py

Modified makefile and implemented belonging.py using income.py as basis

Implement Belonging Extract Step

---

pipeline/Makefile
pipeline/extract/disabilities.py

Branches can be automatically merged

extracted DIS data

---

pipeline/Makefile
pipeline/transform/belonging.py

Modified makefile and implemented belonging.py in transform using income.py in transform as a basis. Added clarification to documentation in belonging.py regarding the split of the geoid.

Implement Belonging Transform Operations

---

pipeline/Makefile
pipeline/transform/disabilities.py

Created disabilities.py using income.py as a template and modified Makefile to output transformed disabilities data.

Transform disabilities

---

pipeline/Makefile
pipeline/load/belonging.sql
pipeline/tests/database_test.py
run.sh

Implemented using a similar schema, modified makefile with belonging.txt placed using existing convention. Results tested and compared using SQLite in Cloud9, data is properly displayed and matches belonging.csv data.

Implement Belonging Load Operation

---

notebooks/fabrego/My Example Notebook.ipynb

Added folder for Jupyter notebook using my hawk username

Fabrego notebook

---

notebooks/aozturk2/My Example Notebook.ipynb

Asude notebook

---

api/metrics/community.py
api/metrics/community_test.py

Added the implementation of the Belonging Metric into the Community Area metrics, using existing code structure as a basis and returning the community area number and the rate of belonging. Also wrote some basic unit tests.

Implementation of Belonging Metric

---

pipeline/Makefile
pipeline/extract/belonging.py
pipeline/load/belonging.sql
pipeline/tests/database_test.py
pipeline/transform/belonging.py
pipeline/utils/testing.py

Began backend implementation for a timeline metric for the Belonging Dataset. Modified both Belonging Extract and Transform, as well as unit tests and table schema. Some modifications of changing lists to sets

Offline Belonging Timeline

---

notebooks/wpurificacion/My Example Notebook.ipynb

Create jupyter notebook folder

Create my notebooks folder

---

pipeline/Makefile
pipeline/load/rent_burdened_households.sql

Trying to load RBU data into database

Load Rent burden household

---

api/endpoints/rideshare.py
api/metrics/rideshare.py
api/metrics/rideshare_test.py

This is a real metric that can be used for pie charts!
Example request URL:
```
http://3.141.21.195:5000/rideshare/total_trips_by_pickup_part_and_year
```

Add metric for total rideshare trips by part of city.

---

api/metrics/rent_burdened.py
api/metrics/rent_burdened_test.py

Might add a few more methods, please check if I'm on the right page.

Metric implementation and metric test attempt for Rent Burdened Household

---

notebooks/lalkatout/My Example Notebook.ipynb

Create my notebooks folder.

---

api/metrics/community_test.py

The tests for the disability rate metric all pass, but two other tests do not. 
```
pipeline/tests/database_test.py::test_table_counts FAILED
pipeline/tests/database_test.py::test_belonging FAILED 
```
I updated my repo following the thread in "#help" between Vinesh and Asude, but the tests continue to fail. The only file I modified is community_test.py

Disabilities metrics tests

---

notebooks/sperveen/My Example Notebook.ipynb
pipeline/Makefile
pipeline/transform/traffic_intensity.py

Transformed traffic_intensity dataset in py file

Traffic intensity transform

---

api/metrics/yearly.py
api/metrics/yearly_test.py
app/components/questions/BelongingRates.js
app/site/questions.js

Implemented a Frontend example for the Belonging Dataset, includes a basic pie chart. Also includes minor changes among yearly.py and yearly_test.py to maintain consistency with naming.

Frontend Belonging

---

pipeline/transform/sidewalk_cafe.py

Remove area based metrics

---

pipeline/Makefile
pipeline/load/sidewalk_cafe.sql
pipeline/transform/sidewalk_cafe.py

Sidewalk cafe load

---

docs/pages/new_endpoint.md

remove step that manually activates virtual environment

Remove venv reference from new_endpoint.md

---

api/metrics/rent_burdened.py
api/metrics/rent_burdened_test.py

Just making sure that the method names are less confusing

Minor naming changes for rent burdened household methods

---

notebooks/sperveen/My Example Notebook.ipynb
pipeline/Makefile
pipeline/load/traffic_intensity.sql

Traffic intensity load

---

pipeline/transform/taxi_trips.py

I decided to just fill null values in pickup and dropoff community area columns with 0's rather than delete the entire row

updated transformed taxi data

---

api/metrics/sidewalk_cafe.py
api/metrics/sidewalk_cafe_test.py
pipeline/extract/sidewalk_cafe.sql
pipeline/load/sidewalk_cafe.sql
pipeline/tests/database_test.py
pipeline/transform/sidewalk_cafe.py

Extract all sidewalk cafe permit data

Extracted all of the remaining sidewalk cafe permits

---

api/endpoints/community.py
api/endpoints/taxitrips.py
api/metrics/community.py
api/metrics/taxitrips.py
api/metrics/taxitrips_test.py
api/questions/taxitrips.py
app/site/metrics.js
pipeline/extract/taxi_trips.sql

I'm dying but it has been done hopefully

added metrics to community/scatter view

---

app/components/questions/SidewalkCafePermitsYears.js
app/site/questions.js

Add a new question about sidewalk cafe permits per year

Add sidewalk cafe chart

---

app/pages/_document.js

Add Contentsecuritypolicy header

---

api/endpoints/question.py
api/metrics/sidewalk_cafe.py
api/questions/sidewalk_search.py
app/components/questions/SidewalkCafePermitSearch.js
app/site/questions.js
app/styles/app.css

Added a new question that lets visitors search for sidewalk permits by restaurant name.
Does this new feature have any security vulnerabilities?

Search for sidewalk permits

---

pipeline/Makefile
pipeline/tests/database_test.py

CTA_train_stops is not present on the server

added line back into Makefile for cta_train_stops

---

api/endpoints/question.py
api/questions/taxitrips.py
api/questions/taxitrips_test.py
app/components/questions/TaxiMostCommonDropoff.js
app/site/questions.js
package.json
yarn.lock

part one of my frontend component

frontend component for most common dropoff locations

---

app/site/metrics.js

To fix the error on the production website when clicking on the metric selector.

Hotfix: Add dataset property to sidewalk cafe scatter metric

---

.gitignore
app/cypress.json
app/package.json
app/tests/e2e/integration/timeline_test.js
app/tests/e2e/plugins/index.js
app/tests/e2e/support/commands.js

Adds a new Cypress Test that visits the Transithealth website and makes various assertions to ensure the functionality and correctness of the website. 
An example of this running in a VM terminal can be seen below:
And the test being run can be seen with this video. Note that the execution of each command is slowed for readability:
https://user-images.githubusercontent.com/72165627/127908170-51e83b5a-0ddb-40fe-91a2-cf8464f96d2b.mp4
An important issue is that so far Cloud9 dislikes running this test so far, the test may be dependent on resources Cloud9 does not have.

Initial Cypress Test Creation

---

.github/workflows/cypress.yaml

Fixes a small syntax problem with the new Github action, should fix the workflow.

Fixes workflow for Github action

---

app/site/metrics.js
pipeline/tests/database_test.py

Traffic intensity metric app

---

app/components/CommunityScatterExplorer.js

fixed map bug

---

app/components/CommunityScatterExplorer.js
app/components/SearchableMetricSelector.js
app/pages/scatter.js

url can now be used to update scatter graph and search selectors

Searchbar 1 url

---

app/components/Nav.js
app/components/questions/CovidCasesPerRideshare.js
app/components/questions/Sample.js
app/pages/index.js
app/pages/questions/[id].js
app/site/questions.js

- Move home page demo to question
- Remove placeholder questions
- Hide example question
- Remove about page from header
- Fix loading on sample component
- Only load community areas GeoJSON if needed for question

Clean up home page and questions for launch

---

app/site/insights.js

5 insights added for scatter graph

Added insights for scatter graph

---

app/components/questions/TrafficIntensity.js

Translated the questions and year selector in Urdu for the pie chart

Added Text translation in Urdu

---

app/components/questions/TrafficIntensity.js
app/site/questions.js

Traffic intensity question urdu translation
