scarletstudio/transithealth

- api/README.md
- api/scripts/time_endpoints.py
- docs/README.md
- docs/time_api_requests.md
Added script and documentation. More could be done to make this convenient for developers (or perhaps it would be better to use an established tool for request timing or even load testing), but I think that could make a good extra engineering task for one of the students.
> Add script to time endpoints.

- app/components/Notification.js
- app/pages/about.js
- app/pages/explorer.js
- app/pages/index.js
- app/pages/questions.js
- app/pages/questions/[id].js
- app/pages/scatter.js
- app/pages/timeline.js
- app/styles/app.css
We use the Heroku free tier, so if our server does not receive any requests for some time, it will shut down. If it receives another request, it has to wake back up and run all the initialization code before responding to a request.
To help show progress to visitors (and so that they don't think the website is broken), I added a notification to show that the site is connecting to our server. This also sends a request to the server to wake it up. This runs on every page. This wake up request will not be sent if one was sent from this browser within the last five minutes.
Check out this video for a demo. I added a `time.sleep(5)` call to the endpoints to simulate a 5 second wake up time.
https://www.loom.com/share/13c4ca51f4434796983be9077d9ed743
> Add server loading notification.

- .gitignore
- docs/pages/makefiles.md
- docs/pages/setup.md
- pipeline/Makefile
This change will allow developers to skip extracting and transforming rideshare data, which can more than 10 minutes. Later we may use the same process for the taxi data.
This pull request also updates the documentation on how to work with these data archives.
Testing on a remote machine to confirm this works. It works! ✅ 
Caveats:
- We should try to keep the archive size under 100MB, that way we stay below the limits to upload it to cloud-based IDEs.
- Google Drive does not allow automated downloads for files this large, so you have to manually download the archive.
- These Make commands will work for Windows users who followed the setup instructions (installed Cygwin and installed Make via Chocolatey).
> Add Makefile targets for working with archives of large files.

- api/dev.sh
- docs/pages/commands.md
- docs/pages/notebooks.md
- notebooks/start.sh
- run.sh
Sorry! In the agenda for the first mentor meeting, I didn't include the instructions for setting up the interns' Jupyter notebook folders and submitting a pull request for that. Thanks @rbrooks6 for catching that.
The notebook setup instructions were buried in the old setup docs that we no longer use since we now have Cloud9. I made a new page that walks people through setting up their notebooks folder.
Now, you can also start your Jupyter notebook server with the `run notebooks 9` command on Cloud9.
> Rearrange instructions for notebook setup.

- docs/pages/commands.md
- docs/pages/sqlite.md
- run.sh
Context: https://scarletdatastudio.slack.com/archives/C0253HKGP5J/p1626131579008200
- We have sqlite 3.7, which does not support the `.open` command.
- Our whole team is using Python 3.7 on Cloud9.
- The sqlite module comes with Python, ~so if we want sqlite 3.8, we would have to upgrade to Python 3.8.~ (actually, we could install sqlite 3.8 directly and add it to the `requirements.txt`)
- @fabrego524 found a fix: using `sqlite <path_to_db>` to start a session.
For now, I think it would be easiest to use this fix, especially since Python and sqlite 3.7 are supported.
I also took this opportunity to add the `-header -column` flags, which make the query output easier to read.
I have added a `run sqlite` command that will start the CLI, which should be easier to remember.
Example usage: …
> Add command to run SQLite CLI.

- .github/workflows/test.yaml
- api/dev.sh
- run.sh
- Added `-vvl` flags to `run tests` so developers can see the local variables and find out which values cause the test to fail
- Fix GitHub actions config to run unit tests if any Python file changes
- Added an `else` case with message if a developer types a run command that does not have a shortcut
- Added a message to `run api 9` to print the URL with the instance IP where the API is running
> Run command fixes

- app/components/CommunityScatterExplorer.js
Fabian's PR #44 exposed this bug in the community explorer component. If some community areas are missing data for the selected y-axis metric, then the opacity will be computed incorrectly, causing the Chicago map to show the same shade for all areas.
This PR fixes that bug:
- Filters out missing data when computing the max value
- Replaces missing data with zero when computing opacity
Here is a screenshot showing the fix applied to Fabian's branch:
Burnside is the area 47, which is missing the belonging data. It shows up as zero opacity on the map, while the other areas show the variation.
> Fix community explorer to correctly show opacity when values are missing.

- api/endpoints/community.py
- app/site/metrics.js
Added the Belonging Metric into the list of endpoints using existing conventions, one for 2017 and one for 2018. Also added the metrics into metrics.js with names and units.
> Integrate Belonging Metric with Endpoint and Config

- pipeline/extract/covid_spread.sql
Added back `covid_spread.sql` and reran the pipeline. The database is created completely, and all tests pass.
> Reintroduce covid_spread.sql into pipeline

- docs/pages/commands.md
- docs/pages/makefiles.md
- docs/pages/new_dataset.md
- run.sh
Now you can run make commands from the comfort of the `transithealth/` directory!
Before you would have to do:
```bash
source .venv/bin/activate
cd pipeline
make data/extracted/income.csv
```
Now, you can run this command:
```bash
run make data/extracted/income.csv
```
The run command will take care of activating the virtual environment, entering the `pipeline/` directory, and running the `make` command with any arguments that you provide after `run make`. When the command finishes running, your terminal will still be in the `transithealth/` folder.
This means you should no longer have to manually activate the virtual environment or leave the `transithealth/` folder to run common commands!
You can also specify additional arguments for `run pytest` and `run sqlite3`, if needed.
> Add run shortcuts for make, pytest, and sqlite.

- app/components/TimelineExplorer.js
The timeline metric selectors show a different axis than the axis that metric is actually displayed on.
Here is a screencast (2:30) explaining one the bug and the fix:
https://www.loom.com/share/c307ef9cc09e461faa75ee5e23c36c07
> Fixed axis left/right bugs on timeline.

- api/endpoints/timeline.py
- api/metrics/weekly.py
- api/metrics/weekly_test.py
- api/metrics/yearly.py
- api/metrics/yearly_test.py
- api/server.py
- app/components/TimelineExplorer.js
- app/pages/explorer.js
- app/pages/timeline.js
- app/site/metrics.js
- docs/pages/new_endpoint.md
- docs/pages/tasks.md
Fixes #62 
- Revised website copy on frontend to be clear that timeline view supports date-based metrics, not just weekly
- Renamed internal fields to be clear that timeline view supports any metric with a `date` key
- Updated tests, manually tested timeline view and metrics
If you are working on a metric for the timeline view, make sure you pull the latest version from `main` with this PR, that way you don't develop on the old versions and get merge conflicts.
> Refactor timeline view to include metrics besides weekly

- app/components/questions/BelongingRates.js
This was first attempted in I believe both PR #79 and #77 but couldn't be figured out, so I thought it'd be good to find out a solution to the unformatted values being used by the page.
I managed to use Recharts and React API and examples to create custom styling for both piechart label and tooltip, including the change from the unformatted decimal to formatted percentage. I tried doing this while keeping the footprint of the actual piechart code to a minimum, meaning I had to use various `const`s to define the behavior I wanted, which could then be easily plugged into the syntax for the piechart.
The code is a bit inconsistent with itself, the manner in which Recharts interacts with the provided data is a bit confusing. For the custom tooltip here, I couldn't figure out a way to use the …
> Improve Frontend Belonging Formatting

- api/dev.sh
- app/dev.sh
- docs/pages/commands.md
- notebooks/start.sh
- run.sh
New options for running the app, added to the common commands doc.
- **If you are doing frontend work only,** you can use `run app 9 api prod` to run your app in development mode, while using the production API. This means you do not have to run the API on your Cloud9.
- **If you are doing backend work only,** you can use `run app 9 static` to serve a static version of the app, while using your Cloud9 API. This means the frontend will not rebuild on changes, but will be faster to navigate between pages.
Here is a screencast showing a demo: https://www.loom.com/share/7751ee3dd41142e2a4c25159b88d1dce
> New options for run app: hotswap API and serve static site.

- app/components/questions/BelongingRates.js
Implemented a simple selector with a list of all community areas in Chicago. Uses a new function `AreaSelector` that generates every option, and now has a React `useState` to change the page upon a new selection.
An interesting case that may have to be handled in the future is the Burnside Community Area. As was encountered during the metric implementations for belonging, there is no data for Burnside. This is reflected on the page when it is selected.
> Frontend Selector for Belonging Question

- app/components/CommunityScatterExplorer.js
Fixes bug #92 
This screencast explains the cause of the bug (stale data in the custom tooltip) and the solution (detect when the data doesn't have the new metrics and tell the tooltip not to display).
https://www.loom.com/share/88c9b582ac8447cb94ed529cc3c206cd
Thanks @fabrego524 and @wpj0110 for helping find this bug!
Clarifying question from the video:
> In the video, you said that the data inside the custom tooltip is stale. Then why do the metrics in the tooltip change but not the payload?
> Yes, that is something I should have explained in the video. The metrics change because the metrics are passed into the custom tooltip as a property from the parent component. However, the payload is managed by the Recharts library that we use for data visualizations and is not under the control …
> Fix bug where changing metric causes scatter view tooltip to display NaN or crash the app

- api/endpoints/community.py
- app/site/metrics.js
Went ahead and implemented 2 additional years for the Median Income metric, 2017 and 2018. This will expand the data a bit for the scatter plot and provide a bit more data for some questions in the future.
> Added 2 more years for Median Income metric

- app/components/questions/BelongingRates.js
- app/site/questions.js
Implemented a simple check to determine if a particular community area returns `NaN` for its value which is passed to both the pie chart and a new `function generateMessage` which will change the text on the page in case the community area has no present data.
One thing of note is that this particular section of code feels a bit clunky for what it does. This specifically looks at the belonging rate of the area whose data is being transformed, and sees if it is `NaN`. There may be some way to check the value directly, however, I was only able to figure out how to check the formatted string instead.
https://github.com/scarletstudio/transithealth/blob/2a039b783069850ce59a8cf615e1025dfeb1747e/app/components/questions/BelongingRates.js#L53-L60
The new function ensures that the parent component …
> Frontend Belonging Solution for Burnside

- app/components/TimelineExplorer.js
Fixes bug #61 
To try this change out in your Cloud9:
```bash
cd transithealth
git fetch
git checkout fix-timeline-dates
run app 9 api prod
```
- Go to the timeline view
- Remove the default metrics
- Add one of the belonging metrics
- Hover over one of the data points and check if the date is correct
> Hack to fix dates on timeline tooltip.

- pipeline/Makefile
Fixes #107 
Description of the `-p` flag from `man mkdir`:
```
-p, --parents
no error if existing, make parent directories as needed
```
No need to use `-p` for some `mkdir` calls in the Makefile because the folder is deleted before that call in the same step.
> Update mkdir to not fail if directory exists.

- app/components/TimelineExplorer.js
- app/styles/app.css
Fixes #60 
- Changes XAxis from date type to number type, which is better supported by Recharts and allows dataMin and dataMax to work automatically, which dynamically resizes the x-axis domain based on the data.
- Handles the two cases where metrics that have not been selected can be present in the data:
- Hidden via the selector
- Metric was removed via the selector, but since we only removed a metric, we do not make another request to the API
- Changes x-axis ticks to use a format with a short month and numeric year (`Jan 2021`)
- Tries to show a tick every time a new year starts, though Recharts sometimes hides ticks to preserve gaps between ticks
- Makes the metric select element responsive on narrow screens
> Improve timeline view x-axis.

- app/pages/_document.js
NextJS has some struggles related to implementing a Content-Security-Policy.
Long story short, in development NextJS generates and evaluates scripts and styles in an unsafe way. It required some messing around with how our NextJS pages are rendered to add a more secure Content-Security-Policy and keep the current functionality.
For more background, check out these links:
- [GitHub issue on the NextJS repository explaining the challenges](https://github.com/vercel/next.js/issues/256)
- [Article by Rees Morris explaining a workaround](https://reesmorris.co.uk/blog/implementing-proper-csp-nextjs-styled-components)
The [advanced feature in the NextJS documentation](https://nextjs.org/docs/advanced-features/security-headers) did not work. But I was able to use the …
> Create _document for Content-Security-Policy and other headers

- app/components/SearchableMetricSelector.js
- app/components/TimelineExplorer.js
Added a new input search bar within the new modal for the Scatter explorer page, as mentioned in #99. Uses live results rather than needing to press search. Also dynamically displays the current search results based on the input text in the search bar.
> Implemented Search for Scatter modal

- app/components/SearchableMetricSelector.js
- app/styles/app.css
Small change of styling for each metric under the modal. This should make each one more distinguishable in the UI. Also altered element names to use consistent `className` naming schemes in the `SearchableMetricSelector` file's code.
The Modal Before
The Modal After
> Modal Metrics Styling

- api/endpoints/community.py
- app/site/metrics.js
During some testing of the new modal's UI on a mobile platform, I noticed that choosing the `2000 Total Population` metric on the app resulted in an empty scatter plot and a fully opaque map. Logging the value of the data in the code showed that no Population data was being returned. This can be seen below
It was a bit unclear why this was the case, so I did some further testing by pulling the latest for main and running `run pipeline-quick`. After a quick check of the database using SQLite, using the query 
```SQL
SELECT MAX(value), period_end_year
FROM population
GROUP By period_end_year
```
It returned data for years from 2010 to 2019.
I also went ahead and double-checked the Chicago Health Atlas API, and it appears the data for the year 2000 was removed at some point.
I asked @vingkan …
> Remove 2000 Total Population Metric

- app/components/SearchableMetricSelector.js
Applies a fix in regards to #153. Previous behavior was not necessarily a bug, but was a product of when the tag dictionary was sorted. Now the dictionary and groups are sorted based on the current search text rather than all possible metrics. 
The new behavior can be seen below.
> Corrected Modal Grouping Behavior

- app/components/TimelineExplorer.js
Fixes #147 
Very similar root cause and fix as in #103 
**Root Cause:** Timeline view tries to render as soon as the selected metrics change, but the data has not yet arrived, causing an error when it tries to format metrics it does not have yet.
**Solution:** Skip render if no selected metrics are in the data. When the response comes, the timeline chart will be able to render the new metrics.
Recording showing the fix in action:
https://www.loom.com/share/07ae403b62e14115bfd1d9c3886bb16c
> Fix bug where removing metrics from timeline view then adding metrics causes an error.

- app/components/TimelineExplorer.js
Fixes #159 
**Root Cause:** When displaying metrics of different time intervals, Recharts groups data by date and considers dates that don't have a value to be null, creating a gap between points.
**Solution:** Set `connectNulls={true}` to always connect subsequent data points in a series.
**Caveats:** This has the drawback that if a series actually has a null gap in its data, the gap will be connected. We should make sure that any null values are set to zero or another logical value.
Screenshot before (bug):
Screenshot after (fix):
> Connect all points of a metric series, even if dates are missing

- app/components/InsightSearch.js
- app/pages/index.js
- app/site/insights.js
- app/styles/app.css
Clicking on "view insight" takes user to corresponding page (scatter plot) with set x and y axis
> home page now display insights with functioning search

- app/components/SearchableMetricSelector.js
This should apply a fix for #160, the modal now checks if the Input is being focused or not. 
It seems this solution 
```javascript
onClick={focus ? undefined : onClose}
``` 
will work, although I'm not sure if there is a better way of doing this. Opinions or feedback on this would be great.
> Fix for Modal Closing when Input is Focused
